### ISSUE TITLE
Fournir un exemple de configuration du docker

### ISSUE THREAD

**Issue by Flightan** [betagouv/signup.api.gouv.fr-docker#4]
Pour lancer le docker dans un environnement de dev, il faut configurer soit-même les variables du https://github.com/betagouv/api-particulier-courtier-docker/blob/master/docker-compose.yml#L25

Ce serait préférable d'avoir: 
 - une configuration par défaut ou
 - un exemple dans le README

**Comment by pknoth** [comment]
la branche V2 est à jour, je ne sais pas si on continue à maintenir la master. L'idée serait de merge V2 dans master

**Comment by Flightan** [comment]
On doit commencer à penser au merge oui.

**Comment by Flightan** [comment]
Reste à merger V2 avec master
