### ISSUE TITLE
Le port du back est le même que celui utilisé actuellement dans le front

### ISSUE THREAD

**Issue by Flightan** [betagouv/signup.api.gouv.fr-docker#5]
Ce qui fait que l'on doit modifier soit-même https://github.com/betagouv/api-particulier-courtier-docker/blob/master/docker-compose.yml pour pouvoir lancer les deux.

**Comment by pknoth** [comment]
lorsque tu lance le serveur du back manuellement tu peux spécifier un port : `rails s -p 3001`
